/* CREATION DES TABLES */
CREATE TABLE SEGMENT(
    N_SEGMENT VARCHAR(10)PRIMARY KEY,
    NOM_SEGMENT VARCHAR(20)
);

CREATE TABLE SALLE(
    N_SALLE VARCHAR(7) PRIMARY KEY,
    NOM_SALLE VARCHAR(20),
    NB_POSTE INTEGER,
    N_SEGMENT VARCHAR(10) REFERENCES SEGMENT (N_SEGMENT)
);

CREATE TABLE POSTE(
    N_POSTE VARCHAR(7) PRIMARY KEY,
    NOM_POSTE VARCHAR(20) ,
    N_SEGMENT VARCHAR(10) REFERENCES SEGMENT (N_SEGMENT),
    AD VARCHAR(2),
    TYPE_POSTE VARCHAR(20),
    N_SALLE VARCHAR(20) REFERENCES SALLE (N_SALLE)
);

CREATE TABLE LOGICIEL (
   N_LOGICIEL VARCHAR(7) PRIMARY KEY,
   NOM_LOGICIEL VARCHAR(20),
   DATE_ACHAT DATE,
   VERSION VARCHAR(7),
   TYPE_LOGICIEL VARCHAR(7)
);

CREATE TABLE INSTALLER(
  N_POSTE VARCHAR(7) REFERENCES POSTE (N_POSTE),
  N_LOGICIEL VARCHAR(20) REFERENCES LOGICIEL (N_LOGICIEL),
  PRIMARY KEY (N_POSTE, N_LOGICIEL),
  DATE_INST DATE
);

